#!/bin/sh
nix-shell -p cargo pkg-config webkitgtk elmPackages.elm --pure --run "\
	echo '== Building Elm to main.js ==' && \
	cd www && \
	elm make src/Main.elm --output=main.js --optimize && \
	cd .. && \
	echo '== Building Rust project ==' && \
	cargo build --release"
